/*
MANDY EXTRAS by Alexander Abraham a.k.a. "Angel Dollface".
Licensed under the MIT license.
*/

/// Importing the "dir_is"
/// method from the "coutils"
/// crate to check if a
/// directory exists.
use coutils::dir_is;

/// Importing the "file_is"
/// method from the "coutils"
/// crate to check if a
/// file exists.
use coutils::file_is;

/// Importing Mandy's error
/// struct.
use merrors::MandyError;

/// We import the method to create
/// empty text files from the "coutils"
/// crate.
use coutils::create_file;

/// We import the method to write
/// to created files.
use coutils::write_to_file;

/// Generates a Typescript file to serve a static 
/// site in $project/dist.
pub fn generate_server(dir: &String) -> Result<(), MandyError> {
    let dist_path: &String = &format!("{}/dist",dir);
    if dir_is(dist_path){
        let server_mod_url: &String = &String::from("https://angeldollface.art/mandys-house/helpers/server.ts");
        let comments: String = String::from("/* Generated by Mandy. */");
        let code: &String = &format!("{}\nimport {{ serveSite }} from \'{}\';\nserveSite(\'index.html\').then(() => {{}});", comments, server_mod_url);
        let server_path: &String = &format!("{}/{}", dist_path, &"server.ts");
        if file_is(server_path){
            let e: String = format!("\"{}\" already exists.", &server_path);
            return Err::<(), MandyError>(
                MandyError::new(
                    &e.to_string()
                )
            );
        }
        else {
            match create_file(server_path){
                Ok(_x) => {},
                Err(e) => {
                    return Err::<(), MandyError>(
                        MandyError::new(
                            &e.to_string()
                        )
                    );
                }
            };
            match write_to_file(server_path, code){
                Ok(_x) => {},
                Err(e) => {
                    return Err::<(), MandyError>(
                        MandyError::new(
                            &e.to_string()
                        )
                    );
                }
            };
        }
    }
    else {
        let e: String = format!("\"{}\" does not exist.", &dist_path);
        return Err::<(), MandyError>(
            MandyError::new(
                &e.to_string()
            )
        );
    }
    return Ok(());
}