on: [push]
env:
  MANDY_ENV: "production"
name: Mandy CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: "Build Mandy."
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p mandy-bin --release

      - name: "Scaffold a new Mandy site. (short version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- -i mysite -w angeldollface/mandy-template-site
          
      - name: "Compile a Mandy site. (short version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- -c mysite

      - name: "Reset a Mandy site. (short version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- -r mysite
      
      - name: "Cleanup for next run."
        run: rm -rf mysite
      - name: "Scaffold a new Mandy site. (long version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- --inits mysite --wtmpl angeldollface/mandy-template-site

      - name: "Compile a Mandy site. (long version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- --comps mysite

      - name: "Reset a Mandy site. (long version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- --reset mysite

      - name: "Cleanup for next run."
        run: rm -rf mysite
      - name: "Scaffold a new Mandy site. (naked version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- inits mysite wtmpl angeldollface/mandy-template-site

      - name: "Compile a Mandy site. (naked version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- comps mysite
        
      - name: "Reset a Mandy site. (naked version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p mandy-bin -- reset mysite
      
      - name: "Run Vento Oxide tests."
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p vento-oxide

      - name: "Run Dollmarkup tests."
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p dollmarkup
