on: [push]
name: MANDY COMPILER CI
jobs:
  build_and_test:
    name: MANDY COMPILER CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Make an optimized build of the Mandy compiler."
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      #- name: "Compile the example in release mode. (Short version.)"
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: run
      #    args: -- -i example/hello.mandy -o hello -r
      #- name: "Compile the example in release mode. (Long version.)"
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: run
      #    args: -- --input example/hello.mandy --output hello --release